version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
        - "6379:6379"
    expose:
        - "6379"
  vue:
      build:
        context: .
        dockerfile: docker/frontendDockerFile
      container_name: docker-django-vue-frontend
      command: npm run serve
      volumes:
        - .:/app
      ports:
        - "8080:8080"
      depends_on:
        - web